[data]
kitId=0

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino

extra_scripts =
    pre:python/platformio_utf8.py
    post:python/platformio_utf8.py

build_type = debug
debug_tool = esp-builtin
debug_speed = 1000
debug_load_mode = manual
debug_init_break = tbreak setup

monitor_speed = 115200
upload_speed = 460800

build_src_filter = +<esp1.cpp>
build_flags =
    -DKIT_ID=${data.kitId}
    -DKIT_HOSTNAME='"iikit${data.kitId}"'

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    adafruit/Adafruit SSD1306 @ ^2.5.0
    adafruit/Adafruit GFX Library @ ^1.11.0
    adafruit/Adafruit BusIO @ ^1.16.0
    tzapu/WiFiManager @ ^2.0.0
